// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateUser(arg1:string):Promise<main.User>;

export function GetAllRooms():Promise<Array<main.Room>>;

export function GetConnectionStatus():Promise<boolean>;

export function GetCurrentRoom():Promise<main.Room>;

export function GetMode():Promise<string>;

export function GetServerUsers():Promise<Array<main.User>>;

export function Greet(arg1:string):Promise<string>;

export function Invite(arg1:string):Promise<string>;

export function LeaveRoom(arg1:string):Promise<string>;

export function ListAllUsers():Promise<Array<main.User>>;

export function StartHTTPServer(arg1:string):Promise<void>;

export function SyncFromServer():Promise<void>;
