// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetAllRooms() {
  return window['go']['main']['App']['GetAllRooms']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetServerUsers() {
  return window['go']['main']['App']['GetServerUsers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function LeaveRoom(arg1) {
  return window['go']['main']['App']['LeaveRoom'](arg1);
}

export function ListAllUsers() {
  return window['go']['main']['App']['ListAllUsers']();
}

export function SendChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3);
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}

export function SyncFromServer() {
  return window['go']['main']['App']['SyncFromServer']();
}
