// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetAllRooms() {
  return window['go']['main']['App']['GetAllRooms']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function LeaveRoom(arg1) {
  return window['go']['main']['App']['LeaveRoom'](arg1);
}

export function ListAllUsers() {
  return window['go']['main']['App']['ListAllUsers']();
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}
