// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptInvite(arg1, arg2) {
  return window['go']['main']['App']['AcceptInvite'](arg1, arg2);
}

export function ApproveJoinRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApproveJoinRequest'](arg1, arg2, arg3);
}

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetAllRooms() {
  return window['go']['main']['App']['GetAllRooms']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetClipboardItem() {
  return window['go']['main']['App']['GetClipboardItem']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetOperations(arg1, arg2) {
  return window['go']['main']['App']['GetOperations'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function InviteWithRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['InviteWithRoom'](arg1, arg2, arg3);
}

export function JoinRoom(arg1, arg2) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2);
}

export function LeaveRoom(arg1) {
  return window['go']['main']['App']['LeaveRoom'](arg1);
}

export function ListAllUsers() {
  return window['go']['main']['App']['ListAllUsers']();
}

export function RequestJoinRoom(arg1, arg2) {
  return window['go']['main']['App']['RequestJoinRoom'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SetUser(arg1, arg2) {
  return window['go']['main']['App']['SetUser'](arg1, arg2);
}

export function ShareSystemClipboard() {
  return window['go']['main']['App']['ShareSystemClipboard']();
}

export function StartClipboardMonitor() {
  return window['go']['main']['App']['StartClipboardMonitor']();
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}
